### ISSUE TITLE
Should not close open modal if user clicks to submit idea or feedback

### ISSUE THREAD

**Issue by lucasrangit** [ionoid/ionoid#3]
I didn't expect to lose my work as I was adding a device when I clicked to submit an idea/feedback. At least make this another modal that doesn't replace the open one if changes have not been saved. Otherwise, a lot of work could get lost.

**Comment by ubugnu** [comment]
@tixxdz what do you think about this? Should we replace the support/feedback pages by modals?
Knowing that for the time being, if we are downloading an image build, the downloading modal does not disappear when visiting other pages

**Comment by ubugnu** [comment]
Fixed, Idea/feedback links will now open in a new tab.
